In [1]:
from google.colab import drive
drive.mount('/content/drive')

from google.colab import files
!cp /content/drive/Shareddrives/ML_PROJET2/Project_2/helpers.py /content
!cp /content/drive/Shareddrives/ML_PROJET2/Project_2/models.py /content


Mounted at /content/drive


In [2]:
!pip install -q -U keras-tuner

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 128.9/128.9 kB 2.3 MB/s eta 0:00:00


In [3]:
import numpy as np
import tensorflow as tf
import keras_tuner as kt
import tensorflow.keras as keras

from helpers import *
from models import *

In [4]:
# Loaded a set of images
root_dir = "/content/drive/Shareddrives/ML_PROJET2/Project_2/data/test_set_images/"
image_dir = root_dir + "images/"
gt_dir = root_dir + "groundtruth/"

test_imgs = get_images_test(root_dir, 50)


Loading /content/drive/Shareddrives/ML_PROJET2/Project_2/data/test_set_images/test_1/test_1.png
Loading /content/drive/Shareddrives/ML_PROJET2/Project_2/data/test_set_images/test_2/test_2.png
Loading /content/drive/Shareddrives/ML_PROJET2/Project_2/data/test_set_images/test_3/test_3.png
Loading /content/drive/Shareddrives/ML_PROJET2/Project_2/data/test_set_images/test_4/test_4.png
Loading /content/drive/Shareddrives/ML_PROJET2/Project_2/data/test_set_images/test_5/test_5.png
Loading /content/drive/Shareddrives/ML_PROJET2/Project_2/data/test_set_images/test_6/test_6.png
Loading /content/drive/Shareddrives/ML_PROJET2/Project_2/data/test_set_images/test_7/test_7.png
Loading /content/drive/Shareddrives/ML_PROJET2/Project_2/data/test_set_images/test_8/test_8.png
Loading /content/drive/Shareddrives/ML_PROJET2/Project_2/data/test_set_images/test_9/test_9.png
Loading /content/drive/Shareddrives/ML_PROJET2/Project_2/data/test_set_images/test_10/test_10.png
Loading /content/drive/Shareddrives/ML

In [5]:
checkpoint_path = '/content/drive/Shareddrives/ML_PROJET2/Project_2/Models/from_A32RD'
model_A32RD = build_unet(dropout = 0.1, activation='relu', regularization=1e-5)
model_A32RD.compile(optimizer='adam',
                loss=TverskyLoss,
                metrics=['accuracy'])
model_A32RD.load_weights(checkpoint_path)

In [6]:
predictions = model_A32RD.predict(test_imgs)

2/2 [==============================] - 65s 25s/step


In [7]:
pred = np.argmax(predictions, 3)

In [8]:
masks_to_submission("/content/drive/Shareddrives/ML_PROJET2/Project_2/augment_A32RD.csv", pred)

In [9]:
np.where(predictions>0.25)

(array([ 0,  0,  0, ..., 49, 49, 49]),
 array([  0,   0,   0, ..., 607, 607, 607]),
 array([  0,   1,   2, ..., 605, 606, 607]),
 array([0, 0, 0, ..., 0, 0, 0]))